---
version: "1"
io:
  i2c:
    1:
      in:
        - name: taster
          address: 0x38
          chip: pcf8574
      out:
        - name: relays
          address: 0x20
          chip: pcf8574
automation:
  lights:
    - name: kueche
      input:
        path: taster[2]
      output: relays[3]
    - name: stiege
      input:
        path: taster[1]
      output: relays[1]
