---
version: "1"
io:
  i2c:
    1:
      in:
        - name: taster
          address: 0x38
          chip: pcf8574
      out:
        - name: relays1
          address: 0x20
          chip: pcf8574
        - name: relays2
          address: 0x21
          chip: mcp7311
automation:
  blinds:
    - name: wohnzimmer-sued1
      input1:
        path: taster[2]
        modify: single
      input2:
        path: taster[3]
        modify: single
      output1: relays1[0]
      output2: relays1[1]
      mqtt: /homeautomation/blinds/wohnzimmer-sued1

  lights:
    - name: Wohnzimmer
      input:
        path: taster[0]
        modify: double
      output: relays1[2]
      mqtt: /homeautomation/lights/wohnzimmer
    - name: Stiegenabgang
      input:
        path: taster[1]
        modify: single
      output: relays1[3]
    - name: Stiegenaufgang
      input:
        path: taster[1]
        modify: double
  mqtt:
    - topic: /homeautomation/blinds/schlafzimmer
      message: up
      input:
        path: taster[4]
        modify: double
