---
version: "1"
io:
  i2c:
    # one go routine per bus
    1:
      in:
        - name: taster
          address: 0x38
          chip: pcf8574
      out:
        - name: relays
          address: 0x20
          chip: pcf8574
automation:
  lights:
    # one go routine per light
    - name: kueche
      inputs:
        local:
          name: taster[2]
      output: relays[3]
    - name: stiege
      inputs:
        local:
          name: taster[1]
      output: relays[1]
