---
version: "1"
io:
  i2c:
    1:
      in:
        - name: taster
          address: 0x38
          chip: pcf8574
      out:
        - name: relays1
          address: 0x20
          chip: pcf8574
        - name: relays2
          address: 0x21
          chip: mcp7311
automation:
  blinds:
    - name: wohnzimmer-sued1
      input1: taster[2]
      input2: taster[3]
      output1: relays1[0]
      output2: relays1[1]
  lights:
    - name: wohnzimmer
      inputs:
        local:
          name: taster[0]
          modify: double
        mqtt: /homeautomation/inputs/schalter1
      output: relays1[2]
    - name: Stiegenabgang
      inputs:
        local:
          name: taster[1]
          modify: r_trig
      output: relays1[3]
  mqtt:
    - topic: /homeautomation/inputs/schalter2
      inputs:
        local:
          name: taster[4]
          modify: double
